---

- name: INCLUDE | Setup
  include: setup.yml

- name: INCLUDE | Configuration
  include: config.yml

- name: INCLUDE | SSL
  include: ssl.yml

- name: INCLUDE | Plugins
  include: plugins.yml

- name: Ensure Logstash is started and enabled on boot.
  service: "name=logstash state=started enabled={{ logstash_enabled_on_boot }}"
  when: not logstash_is_docker
