---

- name: COMMAND | Get list of installed plugins
  command: "{{ logstash_bin_plugin }} list"
  register: logstash_plugins_list
  changed_when: false

- name: COMMAND | Install configured plugins
  command: "{{ logstash_bin_plugin }} install {{ item }}"
  with_items: "{{ logstash_install_plugins }}"
  when: "item not in logstash_plugins_list.stdout"
  notify: restart logstash
